algoritmo "semnome"
// Função :
// Autor :
// Data : 08/07/2022
// Seção de Declarações 
var
contador , n1 , n2  : inteiro
inicio
escreva ("Até quanto voce quer contar? ")
leia (n1)
escreva ("de quantas em quantas unidades: ")
leia (n2)

                 contador <- 0
                 enquanto (contador <= n1) faca
                 escreval (contador)
                 contador <- contador + n2


                 
fimenquanto

fimalgoritmo

